#ifndef OPCODE_TYPE_INCLUDED
#define OPCODE_TYPE_INCLUDED

enum ArmOpcodeType
{
    BRANCH,
    BX,
    SWI,
    UNDEFINED,
    
    ALU,
    MULTIPLY,
    MULTIPLY_LONG,

    PSR_TRANSFER,
    SINGLE_DATA_TRANSFER,
    HALF_WORD_SIGNED_DATA_TRANSFER,
    BLOCK_DATA_TRANSFER,
    SWAP,
};

enum ThumbOpcodeType
{
    MOVE_SHIFTED_REGISTER,
    ADD_SUBTRACT,
    MOVE_COMPARE_ADD_SUBTRACT_IMMEDIATE,
    ALU_OPERATION,
    HI_REGISTER_OPERATIONS_BRANCH_EXCHANGE,
    PC_RELATIVE_LOAD,
    LOAD_STORE_REGISTER_OFFSET,
    LOAD_STORE_SIGN_EXTENDED_BYTE_HALFWORD,
    LOAD_STORE_IMMEDIATE_OFFSET,
    LOAD_STORE_HALFWORD,
    LOAD_STORE_SP_RELATIVE,
    LOAD_ADDRESS,
    ADD_OFFSET_TO_STACK_POINTER,
    PUSH_POP_REGISTERS,
    MULTIPLE_LOAD_STORE,
    BRANCH_CONDITIONAL,
    BRANCH_UNCONDITIONAL,
    SOFTWARE_INTERRUPT,
    LONG_BRANCH_WITH_LINK
};

#endif